# Generated by Django 4.1.7 on 2023-04-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_transactions_24h', models.PositiveIntegerField()),
                ('avg_transaction_fee_24h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('active_wallets_24h', models.PositiveIntegerField()),
                ('total_transactions_7d', models.PositiveIntegerField()),
                ('avg_transaction_fee_7d', models.DecimalField(decimal_places=10, max_digits=20)),
                ('active_wallets_7d', models.PositiveIntegerField()),
                ('total_transactions_30d', models.PositiveIntegerField()),
                ('avg_transaction_fee_30d', models.DecimalField(decimal_places=10, max_digits=20)),
                ('active_wallets_30d', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_transactions_24h', models.PositiveIntegerField()),
                ('total_transaction_fee_24h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('active_wallets_24h', models.PositiveIntegerField()),
                ('total_transactions_7d', models.PositiveIntegerField()),
                ('total_transaction_fee_7d', models.DecimalField(decimal_places=10, max_digits=20)),
                ('active_wallets_7d', models.PositiveIntegerField()),
                ('total_transactions_30d', models.PositiveIntegerField()),
                ('total_transaction_fee_30d', models.DecimalField(decimal_places=10, max_digits=20)),
                ('active_wallets_30d', models.PositiveIntegerField()),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='ShroomAPIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('blockchain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.blockchain')),
                ('dapp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dapp')),
            ],
        ),
    ]
