# Generated by Django 4.1.7 on 2023-04-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shroomapiquery',
            name='api_key',
        ),
        migrations.AddField(
            model_name='shroomapiquery',
            name='sub_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shroomapiquery',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shroomapiquery',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shroomapiquery',
            name='query',
            field=models.TextField(default=''),
        ),
    ]
