# Generated by Django 4.1.7 on 2023-04-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_blockchain_shroom_api_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingscore',
            name='dapp',
        ),
        migrations.DeleteModel(
            name='Dapp',
        ),
    ]
