# Generated by Django 4.1.7 on 2023-04-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_blockchain_active_wallets_24h_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='Platform_recent_activity',
        ),
        migrations.DeleteModel(
            name='TrendingScore',
        ),
    ]
