# Generated by Django 3.2 on 2023-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_blockchain_platform_recent_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_recent_activity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
