# Generated by Django 3.2 on 2023-04-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_platform_recent_activity_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('builder', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hashtags', models.CharField(help_text='Comma-separated list of hashtags', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consumer_key', models.CharField(max_length=200)),
                ('consumer_secret', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('access_token_secret', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
