# Generated by Django 3.2 on 2023-04-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_blockchaindashboard_twitterbot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockchainDashboard',
            new_name='BlockchainDashboards',
        ),
    ]
