# Generated by Django 3.2 on 2023-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_blockchaindashboard_blockchaindashboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_recent_activity',
            name='new_users_24h',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='platform_recent_activity',
            name='new_users_30d',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='platform_recent_activity',
            name='new_users_7d',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
