# Generated by Django 3.2 on 2023-04-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_blockchaindashboards_start_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaindashboards',
            name='tweet_img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
